### ISSUE TITLE
json issues with external webserver

### ISSUE THREAD

**Issue by Pr0prioceptid** [adsb-related-code/dump1090-mutability#3]
webserver displays: AJAX call failed (error: not found) Maybe dump1090 is no longer running?
log displays nothing.
/run/dump1090-mutability is empty.
cli display functions as normal.

**Comment by hipposec** [comment]
I had this issue and found out you have to add --write-json /run/dump1090-mutability/ to the command when you start it. I also had to manually make /run/dump1090-mutability and open up the permissions. Hope this helps.
